version: '3.8'

services:
  hazelcast-demo:
    image: hazelcast/hazelcast:5.3.2
    container_name: hazelcast-demo
    environment:
      JAVA_OPTS : "-Dhazelcast.config=/opt/hazelcast-server.xml
                     -Dhazelcast.rest.enabled=true
                     -Dhazelcast.mancenter.enabled=true
                     -Dlogger.com.hazelcast=debug
                     -Dlogging.level.com.hazelcast=debug
                     -Dhazelcast.mancenter.url=http://hazelcast-management:8080/hazelcast-mancenter"
    volumes:
      - ./config/hazelcast/hazelcast-server.xml:/opt/hazelcast-server.xml:ro
    ports:
      - "5701:5701"

  hazelcast-management-demo:
    image: hazelcast/management-center:5.3.2
    container_name: hazelcast-management-demo
    restart: unless-stopped
    ports:
      - "9090:8080"